export const SCREENS_KEY = {
  LOGIN: 'LOGIN',
  SMS: 'SMS',
  WELCOME: 'WELCOME',
  INFO: 'info',
  SETTINGS: 'SETTINGS',
  AUTO: 'AUTO',
  EDIT: 'EDIT',
  REGISTER: 'REGISTER',
};

export const TABS_KEY = {
  CHILDREN: 'TAB_CHILDREN',
  INFO: 'TAB_INFO',
  KNOWLEDGE: 'TAB_KNOWLEDGE',
  AUTO: 'TAB_AUTO',
  SETTING: 'TAB_SETTING',
};
